version: '3'

services:
  postgres:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - postgres.env
